package ventanas;

import clases.ImpresionPdf;
import clases.Conexion;
import java.sql.*;

import java.awt.HeadlessException;
import java.awt.Toolkit;

import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Locale;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import java.util.Date;

/**
 *
 * @author Javier Toro
 */
public class Capturista extends javax.swing.JFrame {

    String user, nombre_usuario;
    int sesion_usuario;

    public int cmb() {
        int cmb_pr;
        cmb_pr = cmb_VentJard.getSelectedIndex();
        return cmb_pr;
    }

    public int cmb2() {
        int cmb_jp;
        cmb_jp = cmb_JuguProv.getSelectedIndex();
        return cmb_jp;
    }

    public int cmb3() {
        int tipo;
        tipo = cmb_tipo.getSelectedIndex();
        return tipo;
    }

    public Capturista() {
        initComponents();
        user = Login.user;
        sesion_usuario = Administrador.sesion_usuario;

        setSize(573, 350);
        setResizable(false);
        setTitle("Capturista - Sesión de " + user);
        setLocationRelativeTo(null);

        if (sesion_usuario == 1) {
            setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        } else {
            setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        }

        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel_Wallpaper.getWidth(),
                jLabel_Wallpaper.getHeight(), java.awt.Image.SCALE_DEFAULT));
        jLabel_Wallpaper.setIcon(icono);
        this.repaint();

        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
                    "select nombre_usuario from usuarios where username = '" + user + "'");
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                nombre_usuario = rs.getString("nombre_usuario");
                jLabel_NombreUsuario.setText("Bienvenido " + nombre_usuario);
            }
        } catch (SQLException e) {
            System.out.println("Error en consultar nombre de capturista.");
        }
        mostrarjardin();
        mostrarproveedor();

    }

    @Override
    public java.awt.Image getIconImage() {
        java.awt.Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedCapturista = new javax.swing.JTabbedPane();
        jPanelVentas = new javax.swing.JPanel();
        jButton_RegistrarCompra = new javax.swing.JButton();
        jButton_GestionarCompra = new javax.swing.JButton();
        jButton_ImprimirCompra = new javax.swing.JButton();
        jLabelRegComp = new javax.swing.JLabel();
        jLabelGestComp = new javax.swing.JLabel();
        jLabelTituloComp = new javax.swing.JLabel();
        jLabelImpComp = new javax.swing.JLabel();
        jPanelJardines = new javax.swing.JPanel();
        jLabel_TitJardin = new javax.swing.JLabel();
        jLabelRegJard = new javax.swing.JLabel();
        jLabelGestJar = new javax.swing.JLabel();
        jLabelImpJar = new javax.swing.JLabel();
        jButton_RegistrarJardin = new javax.swing.JButton();
        jButton_GestionarJardines = new javax.swing.JButton();
        jButton_Imp_Jard = new javax.swing.JButton();
        jPanelJuguetes = new javax.swing.JPanel();
        jButton_RegistrarJuguete = new javax.swing.JButton();
        jButton_GestionarJuguetes = new javax.swing.JButton();
        jButton_ImprimirJuguetes = new javax.swing.JButton();
        jLabelImpJug = new javax.swing.JLabel();
        jLabelGesJug = new javax.swing.JLabel();
        jLabelRegJug = new javax.swing.JLabel();
        jLabelTitJug = new javax.swing.JLabel();
        jPanelProveedores = new javax.swing.JPanel();
        jButton_RegistrarProve = new javax.swing.JButton();
        jButton_GestionarProve = new javax.swing.JButton();
        jButton_ImprimirProve = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanelInformes = new javax.swing.JPanel();
        jButton_VentasJard = new javax.swing.JButton();
        jButton_JugueProv = new javax.swing.JButton();
        jButton_ListaPrecio = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        cmb_VentJard = new javax.swing.JComboBox();
        cmb_JuguProv = new javax.swing.JComboBox();
        cmb_tipo = new javax.swing.JComboBox<String>();
        jPanelvVisitas = new javax.swing.JPanel();
        jButton_RegistrarVisita = new javax.swing.JButton();
        jButton_GestionarVisita = new javax.swing.JButton();
        jButton_ImprimirVisita = new javax.swing.JButton();
        jLabelRegComp1 = new javax.swing.JLabel();
        jLabelGestComp1 = new javax.swing.JLabel();
        jLabelTituloComp1 = new javax.swing.JLabel();
        jLabelImpComp1 = new javax.swing.JLabel();
        jLabel_NombreUsuario = new javax.swing.JLabel();
        jLabel_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 102));
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedCapturista.setBackground(new java.awt.Color(0, 204, 102));
        jTabbedCapturista.setPreferredSize(new java.awt.Dimension(570, 320));

        jPanelVentas.setBackground(new java.awt.Color(0, 204, 102));
        jPanelVentas.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton_RegistrarCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Reg-Jar.png"))); // NOI18N
        jButton_RegistrarCompra.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_RegistrarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RegistrarCompraActionPerformed(evt);
            }
        });

        jButton_GestionarCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Reg-Jar.png"))); // NOI18N
        jButton_GestionarCompra.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_GestionarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GestionarCompraActionPerformed(evt);
            }
        });

        jButton_ImprimirCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/impresora.png"))); // NOI18N
        jButton_ImprimirCompra.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_ImprimirCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ImprimirCompraActionPerformed(evt);
            }
        });

        jLabelRegComp.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelRegComp.setText("Registrar Ventas");

        jLabelGestComp.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelGestComp.setText("Gestionar Ventas");

        jLabelTituloComp.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        jLabelTituloComp.setText("Opciones de Ventas");

        jLabelImpComp.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelImpComp.setText("Imprimir Ventas");

        javax.swing.GroupLayout jPanelVentasLayout = new javax.swing.GroupLayout(jPanelVentas);
        jPanelVentas.setLayout(jPanelVentasLayout);
        jPanelVentasLayout.setHorizontalGroup(
            jPanelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVentasLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_RegistrarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelVentasLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabelRegComp)))
                .addGap(62, 62, 62)
                .addGroup(jPanelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_GestionarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelGestComp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(jPanelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_ImprimirCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelImpComp))
                .addGap(55, 55, 55))
            .addGroup(jPanelVentasLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabelTituloComp)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelVentasLayout.setVerticalGroup(
            jPanelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVentasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTituloComp)
                .addGap(33, 33, 33)
                .addGroup(jPanelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelVentasLayout.createSequentialGroup()
                        .addComponent(jButton_ImprimirCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelImpComp))
                    .addGroup(jPanelVentasLayout.createSequentialGroup()
                        .addComponent(jButton_GestionarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelGestComp))
                    .addGroup(jPanelVentasLayout.createSequentialGroup()
                        .addComponent(jButton_RegistrarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelRegComp)))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jTabbedCapturista.addTab("Ventas", jPanelVentas);

        jPanelJardines.setBackground(new java.awt.Color(0, 204, 102));

        jLabel_TitJardin.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        jLabel_TitJardin.setText("Opciones Jardin");

        jLabelRegJard.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelRegJard.setText("Registrar Jardin");

        jLabelGestJar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelGestJar.setText("Gestionar Jardin");

        jLabelImpJar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelImpJar.setText("Imprimir Jardines");

        jButton_RegistrarJardin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Reg-Jar.png"))); // NOI18N
        jButton_RegistrarJardin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_RegistrarJardin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RegistrarJardinActionPerformed(evt);
            }
        });

        jButton_GestionarJardines.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Gest_Jard.png"))); // NOI18N
        jButton_GestionarJardines.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_GestionarJardines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GestionarJardinesActionPerformed(evt);
            }
        });

        jButton_Imp_Jard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/impresora.png"))); // NOI18N
        jButton_Imp_Jard.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Imp_Jard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Imp_JardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelJardinesLayout = new javax.swing.GroupLayout(jPanelJardines);
        jPanelJardines.setLayout(jPanelJardinesLayout);
        jPanelJardinesLayout.setHorizontalGroup(
            jPanelJardinesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJardinesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelJardinesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_TitJardin)
                    .addGroup(jPanelJardinesLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanelJardinesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_RegistrarJardin, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelRegJard))
                        .addGap(60, 60, 60)
                        .addGroup(jPanelJardinesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_GestionarJardines, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelGestJar))
                        .addGap(59, 59, 59)
                        .addGroup(jPanelJardinesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelImpJar)
                            .addComponent(jButton_Imp_Jard, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanelJardinesLayout.setVerticalGroup(
            jPanelJardinesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJardinesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_TitJardin)
                .addGap(39, 39, 39)
                .addGroup(jPanelJardinesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton_RegistrarJardin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_GestionarJardines, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Imp_Jard, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanelJardinesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRegJard)
                    .addComponent(jLabelGestJar)
                    .addComponent(jLabelImpJar))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jTabbedCapturista.addTab("Jardines", jPanelJardines);

        jPanelJuguetes.setBackground(new java.awt.Color(0, 204, 102));

        jButton_RegistrarJuguete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Reg-Jar.png"))); // NOI18N
        jButton_RegistrarJuguete.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_RegistrarJuguete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RegistrarJugueteActionPerformed(evt);
            }
        });

        jButton_GestionarJuguetes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Gest_Jug.png"))); // NOI18N
        jButton_GestionarJuguetes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_GestionarJuguetes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GestionarJuguetesActionPerformed(evt);
            }
        });

        jButton_ImprimirJuguetes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/impresora.png"))); // NOI18N
        jButton_ImprimirJuguetes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_ImprimirJuguetes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ImprimirJuguetesActionPerformed(evt);
            }
        });

        jLabelImpJug.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelImpJug.setText("Imprimir Juguetes");

        jLabelGesJug.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelGesJug.setText("Gestionar Juguetes");

        jLabelRegJug.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelRegJug.setText("Registrar Juguetes");

        jLabelTitJug.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        jLabelTitJug.setText("Opciones Juguetes");

        javax.swing.GroupLayout jPanelJuguetesLayout = new javax.swing.GroupLayout(jPanelJuguetes);
        jPanelJuguetes.setLayout(jPanelJuguetesLayout);
        jPanelJuguetesLayout.setHorizontalGroup(
            jPanelJuguetesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJuguetesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelJuguetesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTitJug)
                    .addGroup(jPanelJuguetesLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanelJuguetesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelRegJug)
                            .addComponent(jButton_RegistrarJuguete, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(68, 68, 68)
                        .addGroup(jPanelJuguetesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelGesJug)
                            .addComponent(jButton_GestionarJuguetes, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)
                        .addGroup(jPanelJuguetesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelImpJug)
                            .addComponent(jButton_ImprimirJuguetes, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanelJuguetesLayout.setVerticalGroup(
            jPanelJuguetesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJuguetesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTitJug)
                .addGap(44, 44, 44)
                .addGroup(jPanelJuguetesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton_GestionarJuguetes, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_RegistrarJuguete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_ImprimirJuguetes, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelJuguetesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRegJug)
                    .addComponent(jLabelGesJug)
                    .addComponent(jLabelImpJug))
                .addGap(47, 47, 47))
        );

        jTabbedCapturista.addTab("Juguetes", jPanelJuguetes);

        jPanelProveedores.setBackground(new java.awt.Color(0, 204, 102));
        jPanelProveedores.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton_RegistrarProve.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Reg-Jar.png"))); // NOI18N
        jButton_RegistrarProve.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_RegistrarProve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RegistrarProveActionPerformed(evt);
            }
        });

        jButton_GestionarProve.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Reg-Jar.png"))); // NOI18N
        jButton_GestionarProve.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_GestionarProve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GestionarProveActionPerformed(evt);
            }
        });

        jButton_ImprimirProve.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/impresora.png"))); // NOI18N
        jButton_ImprimirProve.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_ImprimirProve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ImprimirProveActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Registrar Proveedor");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Gestionar Proveedor");

        jLabel15.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        jLabel15.setText("Opciones Proveedores");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("Imprimir Proveedores");

        javax.swing.GroupLayout jPanelProveedoresLayout = new javax.swing.GroupLayout(jPanelProveedores);
        jPanelProveedores.setLayout(jPanelProveedoresLayout);
        jPanelProveedoresLayout.setHorizontalGroup(
            jPanelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProveedoresLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_RegistrarProve, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(65, 65, 65)
                .addGroup(jPanelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_GestionarProve, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_ImprimirProve, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(55, 55, 55))
            .addGroup(jPanelProveedoresLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelProveedoresLayout.setVerticalGroup(
            jPanelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProveedoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addGap(33, 33, 33)
                .addGroup(jPanelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelProveedoresLayout.createSequentialGroup()
                        .addComponent(jButton_ImprimirProve, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16))
                    .addGroup(jPanelProveedoresLayout.createSequentialGroup()
                        .addComponent(jButton_GestionarProve, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14))
                    .addGroup(jPanelProveedoresLayout.createSequentialGroup()
                        .addComponent(jButton_RegistrarProve, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jTabbedCapturista.addTab("Proveedores", jPanelProveedores);

        jPanelInformes.setBackground(new java.awt.Color(0, 204, 102));
        jPanelInformes.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton_VentasJard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Reg-Jar.png"))); // NOI18N
        jButton_VentasJard.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_VentasJard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_VentasJardActionPerformed(evt);
            }
        });

        jButton_JugueProv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Reg-Jar.png"))); // NOI18N
        jButton_JugueProv.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_JugueProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_JugueProvActionPerformed(evt);
            }
        });

        jButton_ListaPrecio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/impresora.png"))); // NOI18N
        jButton_ListaPrecio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_ListaPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ListaPrecioActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("Ventas al jardin:");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("Juguetes segun proveedor");

        jLabel19.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        jLabel19.setText("Informes");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setText("Lista de precio");

        cmb_VentJard.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione" }));

        cmb_JuguProv.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione" }));

        cmb_tipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "Goma Espuma", "Madera", "Plastico", "Todo" }));
        cmb_tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_tipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelInformesLayout = new javax.swing.GroupLayout(jPanelInformes);
        jPanelInformes.setLayout(jPanelInformesLayout);
        jPanelInformesLayout.setHorizontalGroup(
            jPanelInformesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInformesLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanelInformesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_VentasJard, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(cmb_VentJard, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(jPanelInformesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jButton_JugueProv, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_JuguProv, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanelInformesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_ListaPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(cmb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
            .addGroup(jPanelInformesLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelInformesLayout.setVerticalGroup(
            jPanelInformesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInformesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInformesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInformesLayout.createSequentialGroup()
                        .addGroup(jPanelInformesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_ListaPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_JugueProv, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelInformesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelInformesLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInformesLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel18)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanelInformesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmb_JuguProv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelInformesLayout.createSequentialGroup()
                        .addComponent(jButton_VentasJard, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(cmb_VentJard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31))
        );

        jTabbedCapturista.addTab("Informes", jPanelInformes);

        jPanelvVisitas.setBackground(new java.awt.Color(0, 204, 102));
        jPanelvVisitas.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton_RegistrarVisita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Reg-Jar.png"))); // NOI18N
        jButton_RegistrarVisita.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_RegistrarVisita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RegistrarVisitaActionPerformed(evt);
            }
        });

        jButton_GestionarVisita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Reg-Jar.png"))); // NOI18N
        jButton_GestionarVisita.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_GestionarVisita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GestionarVisitaActionPerformed(evt);
            }
        });

        jButton_ImprimirVisita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/impresora.png"))); // NOI18N
        jButton_ImprimirVisita.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_ImprimirVisita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ImprimirVisitaActionPerformed(evt);
            }
        });

        jLabelRegComp1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelRegComp1.setText("Registrar Visita");

        jLabelGestComp1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelGestComp1.setText("Gestionar Visitas");

        jLabelTituloComp1.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        jLabelTituloComp1.setText("Opciones de Visitas");

        jLabelImpComp1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelImpComp1.setText("Imprimir Visitas");

        javax.swing.GroupLayout jPanelvVisitasLayout = new javax.swing.GroupLayout(jPanelvVisitas);
        jPanelvVisitas.setLayout(jPanelvVisitasLayout);
        jPanelvVisitasLayout.setHorizontalGroup(
            jPanelvVisitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelvVisitasLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanelvVisitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_RegistrarVisita, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelvVisitasLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabelRegComp1)))
                .addGap(62, 62, 62)
                .addGroup(jPanelvVisitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_GestionarVisita, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelGestComp1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(jPanelvVisitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_ImprimirVisita, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelImpComp1))
                .addGap(55, 55, 55))
            .addGroup(jPanelvVisitasLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabelTituloComp1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelvVisitasLayout.setVerticalGroup(
            jPanelvVisitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelvVisitasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTituloComp1)
                .addGap(33, 33, 33)
                .addGroup(jPanelvVisitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelvVisitasLayout.createSequentialGroup()
                        .addComponent(jButton_ImprimirVisita, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelImpComp1))
                    .addGroup(jPanelvVisitasLayout.createSequentialGroup()
                        .addComponent(jButton_GestionarVisita, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelGestComp1))
                    .addGroup(jPanelvVisitasLayout.createSequentialGroup()
                        .addComponent(jButton_RegistrarVisita, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelRegComp1)))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jTabbedCapturista.addTab("Visitas", jPanelvVisitas);

        getContentPane().add(jTabbedCapturista, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 570, 277));

        jLabel_NombreUsuario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_NombreUsuario.setText("Bienvenido");
        getContentPane().add(jLabel_NombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirclijButton3ActionPerformed(java.awt.event.ActionEvent evt) {
        this.dispose();
    }
    private void jButton_RegistrarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RegistrarCompraActionPerformed
        RegistroVentas registrarCompras = new RegistroVentas();
        registrarCompras.setVisible(true);
    }//GEN-LAST:event_jButton_RegistrarCompraActionPerformed

    private void jButton_GestionarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GestionarCompraActionPerformed
        GestionarVentas gestionarCompras = new GestionarVentas();
        gestionarCompras.setVisible(true);
    }//GEN-LAST:event_jButton_GestionarCompraActionPerformed

    private void jButton_ImprimirCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ImprimirCompraActionPerformed
        ImpresionPdf RepVet = new ImpresionPdf();
        RepVet.ReporteVentas();
    }//GEN-LAST:event_jButton_ImprimirCompraActionPerformed

    private void jButton_RegistrarJugueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RegistrarJugueteActionPerformed
        RegistroJuguetes registrarJuguete = new RegistroJuguetes();
        registrarJuguete.setVisible(true);
    }//GEN-LAST:event_jButton_RegistrarJugueteActionPerformed

    private void jButton_GestionarJuguetesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GestionarJuguetesActionPerformed
        GestionarJuguetes gestionarJuguetes = new GestionarJuguetes();
        gestionarJuguetes.setVisible(true);
    }//GEN-LAST:event_jButton_GestionarJuguetesActionPerformed

    private void jButton_ImprimirJuguetesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ImprimirJuguetesActionPerformed
        ImpresionPdf RepJug = new ImpresionPdf();
        RepJug.ReporteJuguetes();
    }//GEN-LAST:event_jButton_ImprimirJuguetesActionPerformed

    private void jButton_RegistrarJardinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RegistrarJardinActionPerformed
        RegistroJardines registrarJardin = new RegistroJardines();
        registrarJardin.setVisible(true);
    }//GEN-LAST:event_jButton_RegistrarJardinActionPerformed

    private void jButton_GestionarJardinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GestionarJardinesActionPerformed
        GestionarJardines gestionarJardines = new GestionarJardines();
        gestionarJardines.setVisible(true);
    }//GEN-LAST:event_jButton_GestionarJardinesActionPerformed

    private void jButton_Imp_JardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Imp_JardActionPerformed
        ImpresionPdf RepJar = new ImpresionPdf();
        RepJar.ReporteJardines();
    }//GEN-LAST:event_jButton_Imp_JardActionPerformed

    private void jButton_RegistrarProveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RegistrarProveActionPerformed
        RegistroProveedores registrarProveedor = new RegistroProveedores();
        registrarProveedor.setVisible(true);
    }//GEN-LAST:event_jButton_RegistrarProveActionPerformed

    private void jButton_GestionarProveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GestionarProveActionPerformed
        GestionarProveedores gestionarProveedores = new GestionarProveedores();
        gestionarProveedores.setVisible(true);
    }//GEN-LAST:event_jButton_GestionarProveActionPerformed

    private void jButton_ImprimirProveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ImprimirProveActionPerformed
        ImpresionPdf RepPro = new ImpresionPdf();
        RepPro.ReporteProveedores();
    }//GEN-LAST:event_jButton_ImprimirProveActionPerformed

    private void jButton_VentasJardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VentasJardActionPerformed
        ImpresionPdf RepVenJar = new ImpresionPdf();
        RepVenJar.ReporteVenJar(cmb());
    }//GEN-LAST:event_jButton_VentasJardActionPerformed

    private void jButton_JugueProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_JugueProvActionPerformed
        ImpresionPdf RepProJug = new ImpresionPdf();
        RepProJug.ReporteProJug(cmb2());
    }//GEN-LAST:event_jButton_JugueProvActionPerformed

    private void jButton_ListaPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ListaPrecioActionPerformed
        ImpresionPdf RepProJug = new ImpresionPdf();
        RepProJug.ListaPrecio(cmb3());
    }//GEN-LAST:event_jButton_ListaPrecioActionPerformed

    private void cmb_tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_tipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_tipoActionPerformed

    private void jButton_RegistrarVisitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RegistrarVisitaActionPerformed
        RegistroVisitas registrarVisita = new RegistroVisitas();
        registrarVisita.setVisible(true);
    }//GEN-LAST:event_jButton_RegistrarVisitaActionPerformed

    private void jButton_GestionarVisitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GestionarVisitaActionPerformed
        GestionarVisita gestionarvisita = new GestionarVisita();
        gestionarvisita.setVisible(true);
    }//GEN-LAST:event_jButton_GestionarVisitaActionPerformed

    private void jButton_ImprimirVisitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ImprimirVisitaActionPerformed
        ImpresionPdf RepVisita = new ImpresionPdf();
        RepVisita.ReporteVisita();
    }//GEN-LAST:event_jButton_ImprimirVisitaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Capturista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Capturista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Capturista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Capturista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Capturista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmb_JuguProv;
    private javax.swing.JComboBox cmb_VentJard;
    private javax.swing.JComboBox<String> cmb_tipo;
    private javax.swing.JButton jButton_GestionarCompra;
    private javax.swing.JButton jButton_GestionarJardines;
    private javax.swing.JButton jButton_GestionarJuguetes;
    private javax.swing.JButton jButton_GestionarProve;
    private javax.swing.JButton jButton_GestionarVisita;
    private javax.swing.JButton jButton_Imp_Jard;
    private javax.swing.JButton jButton_ImprimirCompra;
    private javax.swing.JButton jButton_ImprimirJuguetes;
    private javax.swing.JButton jButton_ImprimirProve;
    private javax.swing.JButton jButton_ImprimirVisita;
    private javax.swing.JButton jButton_JugueProv;
    private javax.swing.JButton jButton_ListaPrecio;
    private javax.swing.JButton jButton_RegistrarCompra;
    private javax.swing.JButton jButton_RegistrarJardin;
    private javax.swing.JButton jButton_RegistrarJuguete;
    private javax.swing.JButton jButton_RegistrarProve;
    private javax.swing.JButton jButton_RegistrarVisita;
    private javax.swing.JButton jButton_VentasJard;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelGesJug;
    private javax.swing.JLabel jLabelGestComp;
    private javax.swing.JLabel jLabelGestComp1;
    private javax.swing.JLabel jLabelGestJar;
    private javax.swing.JLabel jLabelImpComp;
    private javax.swing.JLabel jLabelImpComp1;
    private javax.swing.JLabel jLabelImpJar;
    private javax.swing.JLabel jLabelImpJug;
    private javax.swing.JLabel jLabelRegComp;
    private javax.swing.JLabel jLabelRegComp1;
    private javax.swing.JLabel jLabelRegJard;
    private javax.swing.JLabel jLabelRegJug;
    private javax.swing.JLabel jLabelTitJug;
    private javax.swing.JLabel jLabelTituloComp;
    private javax.swing.JLabel jLabelTituloComp1;
    private javax.swing.JLabel jLabel_NombreUsuario;
    private javax.swing.JLabel jLabel_TitJardin;
    private javax.swing.JLabel jLabel_Wallpaper;
    private javax.swing.JPanel jPanelInformes;
    private javax.swing.JPanel jPanelJardines;
    private javax.swing.JPanel jPanelJuguetes;
    private javax.swing.JPanel jPanelProveedores;
    private javax.swing.JPanel jPanelVentas;
    private javax.swing.JPanel jPanelvVisitas;
    private javax.swing.JTabbedPane jTabbedCapturista;
    // End of variables declaration//GEN-END:variables

    void mostrarjardin() {
        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement("select * from jardines");
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                cmb_VentJard.addItem(rs.getString("jardin"));
            }

        } catch (SQLException e) {
            System.err.println("Error en cargar jardines." + e);
            JOptionPane.showMessageDialog(null, "¡¡ERROR jardines!!, contacte al administrador.");
        }
    }

    void mostrarproveedor() {
        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement("select * from proveedor");
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                cmb_JuguProv.addItem(rs.getString("nombre_prov"));
            }

        } catch (SQLException e) {
            System.err.println("Error en cargar provedores." + e);
            JOptionPane.showMessageDialog(null, "¡¡ERROR Proveedores!!, contacte al administrador.");
        }
    }
}
