/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.sql.*;
import clases.Conexion;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Javier
 */
public class GestionarPrecios extends javax.swing.JFrame {

    String user;
    public static String compra_update = "";
    DefaultTableModel model = new DefaultTableModel();

    /**
     * Creates new form GestionarUsuarios
     */
    public GestionarPrecios() {
        initComponents();
        user = Login.user;

        setSize(650, 520);
        setTitle("Manejo de precios - Sesión de " + user);
        setResizable(false);
        setLocationRelativeTo(null);

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel_Wallpaper.getWidth(),
                jLabel_Wallpaper.getHeight(), Image.SCALE_DEFAULT));
        jLabel_Wallpaper.setIcon(icono);
        this.repaint();

        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
                    "select nombre, Precio, Tipo, Costo, proveedor.nombre_prov "
                            + "from juguetes, proveedor WHERE juguetes.Proveedor = proveedor.id_proveedor");
            
            ResultSet rs = pst.executeQuery();

            jTable_precio = new JTable(model);
            jScrollPane1.setViewportView(jTable_precio);

            model.addColumn("Nombre");
            model.addColumn("Precio");
            model.addColumn("Tipo");
            model.addColumn("Costo");
            model.addColumn("Proveedor");
            

            while (rs.next()) {
                Object[] fila = new Object[5];

                for (int i = 0; i < 5; i++) {
                    fila[i] = rs.getObject(i + 1);
                }
                model.addRow(fila);
            }
            cn.close();

        } catch (SQLException e) {
            System.err.println("Error al llenar tabla." + e);
            JOptionPane.showMessageDialog(null, "Error al mostrar información, ¡Contacte al administrador!");
        }
        mostrarproveedor();

    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_precio = new javax.swing.JTable();
        jLabel_footer = new javax.swing.JLabel();
        jButton_Precio = new javax.swing.JButton();
        cmb_tipo = new javax.swing.JComboBox<String>();
        jLabel_SelecProv = new javax.swing.JLabel();
        jTextField_Porcentaje = new javax.swing.JTextField();
        jLabel_Porcentaje = new javax.swing.JLabel();
        cmb_JugProv = new javax.swing.JComboBox();
        jLabel_Seleccion1 = new javax.swing.JLabel();
        jTextField_Porcentaje1 = new javax.swing.JTextField();
        jLabel_Porcentaje1 = new javax.swing.JLabel();
        jButton_PrecioProv = new javax.swing.JButton();
        jLabel_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Manejo de Precios");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        jTable_precio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_precio.setCellSelectionEnabled(true);
        jScrollPane1.setViewportView(jTable_precio);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 640, 150));

        jLabel_footer.setText("Creado por Javier Toro");
        getContentPane().add(jLabel_footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 460, -1, -1));

        jButton_Precio.setText("Cambiar Precio");
        jButton_Precio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_PrecioActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 120, -1));

        cmb_tipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "Goma Espuma", "Madera", "Plastico", "Todo" }));
        cmb_tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_tipoActionPerformed(evt);
            }
        });
        getContentPane().add(cmb_tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 230, -1));

        jLabel_SelecProv.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_SelecProv.setText("Seleccione el proveedor de Juguete para cambiar el precio");
        getContentPane().add(jLabel_SelecProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 360, -1));
        getContentPane().add(jTextField_Porcentaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 130, -1));

        jLabel_Porcentaje.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Porcentaje.setText("Ingrese el porcentaje a aumentar");
        getContentPane().add(jLabel_Porcentaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, -1, -1));

        cmb_JugProv.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione" }));
        getContentPane().add(cmb_JugProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 230, -1));

        jLabel_Seleccion1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Seleccion1.setText("Seleccione el tipo de Juguete a cambiar el precio");
        getContentPane().add(jLabel_Seleccion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));
        getContentPane().add(jTextField_Porcentaje1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, 130, -1));

        jLabel_Porcentaje1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Porcentaje1.setText("Ingrese el porcentaje a aumentar");
        getContentPane().add(jLabel_Porcentaje1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, -1, -1));

        jButton_PrecioProv.setText("Cambiar Precio");
        jButton_PrecioProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_PrecioProvActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_PrecioProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, 120, -1));
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_PrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_PrecioActionPerformed

        int tipo;
        float porcentaje, multip;
        String sql = "";
        tipo = cmb_tipo.getSelectedIndex();
        porcentaje = Float.parseFloat(jTextField_Porcentaje.getText());
        multip = (porcentaje / 100) + 1;
        

        if (tipo == 1) {
            sql = "UPDATE juguetes SET Precio = Precio * '" + multip + "' WHERE  'Goma Espuma' = Tipo";
        } else if (tipo == 2) {
            sql = "UPDATE juguetes SET Precio = Precio * '" + multip + "' WHERE  'Madera' = Tipo";
        } else if (tipo == 3) {
            sql = "UPDATE juguetes SET Precio = Precio * '" + multip + "' WHERE  'Plastico' = Tipo";
        } else if (tipo == 4) {
            sql = "UPDATE juguetes SET  Precio = Precio * '" + multip + "' ";
        }
        try {
            Connection cn1 = Conexion.conectar();
            PreparedStatement pst = cn1.prepareStatement(sql);
                      
            pst.executeUpdate();
            cn1.close();
            jTable_precio.setVisible(false);
            jTable_precio.setVisible(true);

            JOptionPane.showMessageDialog(null, "Actualizacion correcta.");
        } catch (SQLException e) {
            System.out.println("Error en la actualizacion " + e);
        }
        
        
    }//GEN-LAST:event_jButton_PrecioActionPerformed

    private void cmb_tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_tipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_tipoActionPerformed

    private void jButton_PrecioProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_PrecioProvActionPerformed
        
        int jugprov;
        float porcentaje, multip;
        jugprov = cmb_JugProv.getSelectedIndex();
        String sql;
        porcentaje = Float.parseFloat(jTextField_Porcentaje1.getText());
        multip = (porcentaje / 100) + 1;
        
        sql = "UPDATE juguetes SET Precio = Precio * '" + multip + "' WHERE  '" + jugprov + "' = Proveedor";
        
        try {
            Connection cn2 = Conexion.conectar();
            PreparedStatement pst = cn2.prepareStatement(sql);
                      
            pst.executeUpdate();
            cn2.close();
            

            JOptionPane.showMessageDialog(null, "Actualizacion correcta.");
        } catch (SQLException e) {
            System.out.println("Error en la actualizacion " + e);
        }
        
    }//GEN-LAST:event_jButton_PrecioProvActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionarPrecios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmb_JugProv;
    private javax.swing.JComboBox<String> cmb_tipo;
    private javax.swing.JButton jButton_Precio;
    private javax.swing.JButton jButton_PrecioProv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_Porcentaje;
    private javax.swing.JLabel jLabel_Porcentaje1;
    private javax.swing.JLabel jLabel_SelecProv;
    private javax.swing.JLabel jLabel_Seleccion1;
    private javax.swing.JLabel jLabel_Wallpaper;
    private javax.swing.JLabel jLabel_footer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_precio;
    private javax.swing.JTextField jTextField_Porcentaje;
    private javax.swing.JTextField jTextField_Porcentaje1;
    // End of variables declaration//GEN-END:variables

    void mostrarproveedor() {
        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement("select * from proveedor");
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                cmb_JugProv.addItem(rs.getString("nombre_prov"));
            }

        } catch (SQLException e) {
            System.err.println("Error en cargar provedores." + e);
            JOptionPane.showMessageDialog(null, "¡¡ERROR Proveedores!!, contacte al administrador.");
        }
    }


}
