package ventanas;

import java.sql.*;
import clases.Conexion;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author Javier Toro
 */
public class InformacionJuguetes extends javax.swing.JFrame {

    String user = "", juguete_update = "";
    int ID;

    /**
     * Creates new form InformacionJuguetes
     */
    public InformacionJuguetes() {
        initComponents();
        user = Login.user;
        juguete_update = GestionarJuguetes.juguete_update;

        setResizable(false);
        setTitle("Informacion del juguete " + juguete_update + "- Sesion de" + user);
        setLocationRelativeTo(null);

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel_Wallpaper.getWidth(),
                jLabel_Wallpaper.getHeight(), Image.SCALE_DEFAULT));
        jLabel_Wallpaper.setIcon(icono);
        this.repaint();

        jLabel_Titulo.setText("Información del juguete " + juguete_update);

        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
                    "select * from juguetes where nombre = '" + juguete_update + "'");
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                ID = rs.getInt("id_juguetes");

                Text_Nombre.setText(rs.getString("nombre"));
                Text_Precio.setText(rs.getString("Precio"));
                Text_Proveedor.setText(rs.getString("Proveedor"));
                Text_Stock.setText(rs.getString("Stock"));
                Text_Costo.setText(rs.getString("Costo"));

                cmb_Tipo.setSelectedItem(rs.getString("tipo"));

            }
            cn.close();
        } catch (SQLException e) {
            System.err.println("Error en cargar usuario. " + e);
            JOptionPane.showMessageDialog(null, "¡¡ERROR al cargar!!, contacte al administrador.");
        }
    }

     @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Nombre = new javax.swing.JLabel();
        jLabel_Precio = new javax.swing.JLabel();
        jLabel_Costo = new javax.swing.JLabel();
        jLabel_Proveedor = new javax.swing.JLabel();
        jLabel_Tipo = new javax.swing.JLabel();
        jLabel_Stock = new javax.swing.JLabel();
        jLabel_Titulo = new javax.swing.JLabel();
        jLabel_Ayuda = new javax.swing.JLabel();
        Text_Precio = new javax.swing.JTextField();
        Text_Costo = new javax.swing.JTextField();
        Text_Proveedor = new javax.swing.JTextField();
        Text_Stock = new javax.swing.JTextField();
        Text_Nombre = new javax.swing.JTextField();
        cmb_Tipo = new javax.swing.JComboBox();
        jButton_Actualizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_Ayuda = new javax.swing.JTextArea();
        jLabel_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Nombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Nombre.setText("Nombre:");
        getContentPane().add(jLabel_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel_Precio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Precio.setText("Precio:");
        getContentPane().add(jLabel_Precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, -1, -1));

        jLabel_Costo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Costo.setText("Costo:");
        getContentPane().add(jLabel_Costo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel_Proveedor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Proveedor.setText("Proveedor:");
        getContentPane().add(jLabel_Proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, -1, -1));

        jLabel_Tipo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Tipo.setText("Tipo");
        getContentPane().add(jLabel_Tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, -1, -1));

        jLabel_Stock.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Stock.setText("Stock:");
        getContentPane().add(jLabel_Stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel_Titulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Titulo.setText("Informacion");
        getContentPane().add(jLabel_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        jLabel_Ayuda.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Ayuda.setText("Para Guarda las modificaciones");
        getContentPane().add(jLabel_Ayuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));
        getContentPane().add(Text_Precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 190, -1));
        getContentPane().add(Text_Costo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 120, -1));
        getContentPane().add(Text_Proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 190, -1));
        getContentPane().add(Text_Stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 120, -1));
        getContentPane().add(Text_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 150, -1));

        cmb_Tipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Goma Espuma", "Madera", "Plastico" }));
        getContentPane().add(cmb_Tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, -1, -1));

        jButton_Actualizar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Actualizar.setText("Actualizar");
        jButton_Actualizar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 100, 30));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea_Ayuda.setEditable(false);
        jTextArea_Ayuda.setColumns(20);
        jTextArea_Ayuda.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextArea_Ayuda.setRows(5);
        jTextArea_Ayuda.setText("Esta pantalla se usa para \nmodificar los juguetes\nHay que modificar los campos \nGuardar haciendo click en \nel boton Actualizar");
        jTextArea_Ayuda.setAutoscrolls(false);
        jTextArea_Ayuda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(jTextArea_Ayuda);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 240, 120));
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ActualizarActionPerformed

        int tipo_cmb, validacion = 0;
        String nombre, precio, proveedor, costo, stock, tipo_string = "";

        nombre = Text_Nombre.getText().trim();
        proveedor = Text_Proveedor.getText().trim();
        precio = Text_Precio.getText().trim();
        costo = Text_Costo.getText().trim();
        stock = Text_Stock.getText().trim();
        tipo_cmb = cmb_Tipo.getSelectedIndex() + 1;

        if (nombre.equals("")) {
            Text_Nombre.setBackground(Color.blue);
            validacion++;
        }
        if (proveedor.equals("")) {
            Text_Proveedor.setBackground(Color.blue);
            validacion++;
        }
        if (precio.equals("")) {
            Text_Precio.setBackground(Color.blue);
            validacion++;
        }
        if (costo.equals("")) {
            Text_Costo.setBackground(Color.blue);
            validacion++;
        }
        if (stock.equals("")) {
            Text_Stock.setBackground(Color.blue);
            validacion++;
        }

        if (validacion == 0) {

            if (tipo_cmb == 1) {
                tipo_string = "Goma Espuma";
            } else if (tipo_cmb == 2) {
                tipo_string = "Madera";
            } else if (tipo_cmb == 3) {
                tipo_string = "Plastico";
            }

            try {

                Connection cn = Conexion.conectar();
                PreparedStatement pst = cn.prepareStatement(
                        "select nombre from juguetes where nombre = '" + nombre
                        + "' and not id_juguetes = '" + ID + "'");

                ResultSet rs = pst.executeQuery();

                if (rs.next()) {

                    Text_Nombre.setBackground(Color.red);
                    JOptionPane.showMessageDialog(null, "Nombre de juguete ya en uso.");
                    cn.close();

                } else {

                    Connection cn2 = Conexion.conectar();
                    PreparedStatement pst2 = cn2.prepareStatement(
                            "update juguetes set nombre=?, Precio=?, Tipo=?, Costo=?, Proveedor=?, Stock=? "
                            + "where id_juguetes = '" + ID + "'");

                    pst2.setString(1, nombre);
                    pst2.setString(2, precio);
                    pst2.setString(3, tipo_string);
                    pst2.setString(4, costo);
                    pst2.setString(5, proveedor);
                    pst2.setString(6, stock);

                    pst2.executeUpdate();
                    cn2.close();

                    JOptionPane.showMessageDialog(null, "Modificación correcta.");

                }
            } catch (SQLException e) {

                System.err.println("Error al actualizar." + e);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Debes llenar todos los campos");
        }

    }//GEN-LAST:event_jButton_ActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformacionJuguetes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformacionJuguetes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformacionJuguetes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformacionJuguetes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformacionJuguetes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Text_Costo;
    private javax.swing.JTextField Text_Nombre;
    private javax.swing.JTextField Text_Precio;
    private javax.swing.JTextField Text_Proveedor;
    private javax.swing.JTextField Text_Stock;
    private javax.swing.JComboBox cmb_Tipo;
    private javax.swing.JButton jButton_Actualizar;
    private javax.swing.JLabel jLabel_Ayuda;
    private javax.swing.JLabel jLabel_Costo;
    private javax.swing.JLabel jLabel_Nombre;
    private javax.swing.JLabel jLabel_Precio;
    private javax.swing.JLabel jLabel_Proveedor;
    private javax.swing.JLabel jLabel_Stock;
    private javax.swing.JLabel jLabel_Tipo;
    private javax.swing.JLabel jLabel_Titulo;
    private javax.swing.JLabel jLabel_Wallpaper;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea_Ayuda;
    // End of variables declaration//GEN-END:variables
}
