/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.Conexion;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author Javier Toro
 */
public class InformacionJardines extends javax.swing.JFrame {

    String user = "", jardin_update = "";
    int ID;

    /**
     * Creates new form InformacionJardines
     */
    public InformacionJardines() {
        initComponents();
        user = Login.user;
        jardin_update = GestionarJardines.jardin_update;

        setSize(380, 330);
        setResizable(false);
        setTitle("Información del Jardin " + jardin_update + " - Sesión de " + user);
        setLocationRelativeTo(null);

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel_Wallpaper.getWidth(),
                jLabel_Wallpaper.getHeight(), Image.SCALE_DEFAULT));
        jLabel_Wallpaper.setIcon(icono);
        this.repaint();

        jLabel_Titulo.setText("Información del Jardin " + jardin_update);

        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
                    "select * from jardines where Jardin = '" + jardin_update + "'");
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                ID = rs.getInt("id_jardines");

                Text_Jardin.setText(rs.getString("Jardin"));
                Text_Direccion.setText(rs.getString("Direccion"));
                Text_Contacto.setText(rs.getString("Contacto"));
                Text_Telefono.setText(rs.getString("Tel"));
                Text_Email.setText(rs.getString("Email"));

            }
            cn.close();
        } catch (SQLException e) {
            System.err.println("Error en cargar Jardin. " + e);
            JOptionPane.showMessageDialog(null, "¡¡ERROR al cargar!!, contacte al administrador.");
        }
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Titulo = new javax.swing.JLabel();
        jLabel_Jardin = new javax.swing.JLabel();
        jLabel_Direccion = new javax.swing.JLabel();
        Text_Direccion = new javax.swing.JTextField();
        jLabel_Contacto = new javax.swing.JLabel();
        Text_Contacto = new javax.swing.JTextField();
        jLabel_Telefono = new javax.swing.JLabel();
        Text_Telefono = new javax.swing.JTextField();
        jButton_Actualizar = new javax.swing.JButton();
        Text_Jardin = new javax.swing.JTextField();
        Text_Email = new javax.swing.JTextField();
        jLabel_Email = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_ayuda = new javax.swing.JTextArea();
        jLabel_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Titulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_Titulo.setText("Informacion del jardin:");
        getContentPane().add(jLabel_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jLabel_Jardin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Jardin.setText("Jardin:");
        getContentPane().add(jLabel_Jardin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel_Direccion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Direccion.setText("Direccion:");
        getContentPane().add(jLabel_Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, -1));

        Text_Direccion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(Text_Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 130, -1));

        jLabel_Contacto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Contacto.setText("Contacto:");
        getContentPane().add(jLabel_Contacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        Text_Contacto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(Text_Contacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 130, -1));

        jLabel_Telefono.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Telefono.setText("Telefono:");
        getContentPane().add(jLabel_Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, -1, -1));

        Text_Telefono.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(Text_Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 130, -1));

        jButton_Actualizar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton_Actualizar.setText("Actualizar Jardin");
        jButton_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        Text_Jardin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_JardinActionPerformed(evt);
            }
        });
        getContentPane().add(Text_Jardin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 130, -1));

        Text_Email.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(Text_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 130, -1));

        jLabel_Email.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Email.setText("Email:");
        getContentPane().add(jLabel_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextArea_ayuda.setEditable(false);
        jTextArea_ayuda.setColumns(20);
        jTextArea_ayuda.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTextArea_ayuda.setRows(5);
        jTextArea_ayuda.setText("Despues de modificar hacer\nclick en actualizar.\nPara nuevos jardines ir a \nregistrar Jardin");
        jScrollPane1.setViewportView(jTextArea_ayuda);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 170, 80));
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ActualizarActionPerformed
        int validacion = 0;
        String jardin, contacto, direccion, telefono, email;

        jardin = Text_Jardin.getText().trim();
        contacto = Text_Contacto.getText().trim();
        direccion = Text_Direccion.getText().trim();
        telefono = Text_Telefono.getText().trim();
        email = Text_Email.getText().trim();

        if (jardin.equals("")) {
            Text_Jardin.setBackground(Color.blue);
            validacion++;
        }
        if (contacto.equals("")) {
            Text_Contacto.setBackground(Color.blue);
            validacion++;
        }
        if (direccion.equals("")) {
            Text_Direccion.setBackground(Color.blue);
            validacion++;
        }
            if (telefono.equals("")) {
            Text_Telefono.setBackground(Color.blue);
            validacion++;
        }

        if (validacion == 0) {

            try {

                Connection cn = Conexion.conectar();
                PreparedStatement pst = cn.prepareStatement(
                        "select Jardin from jardines where Jardin = '" + jardin
                        + "' and not id_jardines = '" + ID + "'");

                ResultSet rs = pst.executeQuery();

                if (rs.next()) {

                    Text_Jardin.setBackground(Color.red);
                    JOptionPane.showMessageDialog(null, "Nombre de Jardin no disponible.");
                    cn.close();

                } else {

                    Connection cn2 = Conexion.conectar();
                    PreparedStatement pst2 = cn2.prepareStatement(
                            "update jardines set Jardin=?, Direccion=?, Contacto=?, Tel=?, Email=? where id_jardines = '" + ID + "'");

                    pst2.setString(1, jardin);
                    pst2.setString(2, direccion);
                    pst2.setString(3, contacto);
                    pst2.setString(4, telefono);
                    pst2.setString(5, email);

                    pst2.executeUpdate();
                    cn2.close();

                    JOptionPane.showMessageDialog(null, "Modificación correcta.");

                }

            } catch (SQLException e) {
                System.err.println("Error al Actualizar." + e);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Debes llenar todos los campos.");
        }


    }//GEN-LAST:event_jButton_ActualizarActionPerformed

    private void Text_JardinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_JardinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_JardinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformacionJardines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformacionJardines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformacionJardines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformacionJardines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformacionJardines().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Text_Contacto;
    private javax.swing.JTextField Text_Direccion;
    private javax.swing.JTextField Text_Email;
    private javax.swing.JTextField Text_Jardin;
    private javax.swing.JTextField Text_Telefono;
    private javax.swing.JButton jButton_Actualizar;
    private javax.swing.JLabel jLabel_Contacto;
    private javax.swing.JLabel jLabel_Direccion;
    private javax.swing.JLabel jLabel_Email;
    private javax.swing.JLabel jLabel_Jardin;
    private javax.swing.JLabel jLabel_Telefono;
    private javax.swing.JLabel jLabel_Titulo;
    private javax.swing.JLabel jLabel_Wallpaper;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea_ayuda;
    // End of variables declaration//GEN-END:variables
}
