package ventanas;

import java.sql.*;
import clases.Conexion;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author Javier Toro
 */
public class InformacionVentas extends javax.swing.JFrame {

    String user = "";
    int ID, venta_update;

    public InformacionVentas() {
        initComponents();
        user = Login.user;
        venta_update = GestionarVentas.venta_update;

        setSize(610, 291);
        setResizable(false);
        setTitle("Información de las ventas a " + venta_update + " - Sesión de " + user);
        setLocationRelativeTo(null);

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel_Wallpaper.getWidth(),
                jLabel_Wallpaper.getHeight(), Image.SCALE_DEFAULT));
        jLabel_Wallpaper.setIcon(icono);
        this.repaint();

        jLabel_Titulo.setText("Información de la venta a:" + venta_update);

        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
                    "select id_ventas, juguetes.nombre, jardines.Jardin, fecha, "
                            + "FacturaNro, cuotas from ventas, juguetes, jardines "
                            + "WHERE ventas.juguete_id = juguetes.id_juguetes && "
                            + "ventas.jardin_id = jardines.id_jardines && id_ventas = '" + venta_update + "'");
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                ID = rs.getInt("id_ventas");

                txt_jardin.setText(rs.getString("jardines.Jardin"));
                txt_juguete.setText(rs.getString("juguetes.nombre"));
                txt_comprobante.setText(rs.getString("FacturaNro"));
                txt_fecha.setText(rs.getString("fecha"));
                txt_Cuotas.setText(rs.getString("cuotas"));

            }
            cn.close();
        } catch (SQLException e) {
            System.err.println("Error en cargar informacion de venta. " + e);
            JOptionPane.showMessageDialog(null, "¡¡ERROR al cargar!!, contacte al administrador.");
        }

    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Titulo = new javax.swing.JLabel();
        jLabel_Nombre = new javax.swing.JLabel();
        jLabel_Contacto = new javax.swing.JLabel();
        jLabel_RegistradoPor = new javax.swing.JLabel();
        jLabel_footer = new javax.swing.JLabel();
        jLabel_Direccion = new javax.swing.JLabel();
        jButton_Actualizar = new javax.swing.JButton();
        txt_comprobante = new javax.swing.JTextField();
        txt_fecha = new javax.swing.JTextField();
        txt_jardin = new javax.swing.JTextField();
        txt_juguete = new javax.swing.JTextField();
        jLabel_Cuotas = new javax.swing.JLabel();
        txt_Cuotas = new javax.swing.JTextField();
        jLabel_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Titulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel_Titulo.setText("Información de la venta a:");
        getContentPane().add(jLabel_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jLabel_Nombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Nombre.setText("Nombre Jardin:");
        getContentPane().add(jLabel_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel_Contacto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Contacto.setText("Nombre Juguete:");
        getContentPane().add(jLabel_Contacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, -1));

        jLabel_RegistradoPor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_RegistradoPor.setText("Comprobante:");
        getContentPane().add(jLabel_RegistradoPor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel_footer.setText("Creado por Javier Toro");
        getContentPane().add(jLabel_footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, -1, -1));

        jLabel_Direccion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Direccion.setText("Fecha");
        getContentPane().add(jLabel_Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 106, -1, -1));

        jButton_Actualizar.setBackground(new java.awt.Color(153, 153, 255));
        jButton_Actualizar.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jButton_Actualizar.setText("Actualizar Venta");
        jButton_Actualizar.setBorder(null);
        jButton_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 210, 35));

        txt_comprobante.setBackground(new java.awt.Color(153, 153, 255));
        txt_comprobante.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_comprobante.setForeground(new java.awt.Color(255, 255, 255));
        txt_comprobante.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_comprobante.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_comprobante, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 210, -1));

        txt_fecha.setBackground(new java.awt.Color(153, 153, 255));
        txt_fecha.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_fecha.setForeground(new java.awt.Color(255, 255, 255));
        txt_fecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_fecha.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 210, -1));

        txt_jardin.setBackground(new java.awt.Color(255, 255, 102));
        txt_jardin.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_jardin.setForeground(new java.awt.Color(255, 255, 255));
        txt_jardin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_jardin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_jardin.setEnabled(false);
        getContentPane().add(txt_jardin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 210, -1));

        txt_juguete.setBackground(new java.awt.Color(255, 255, 102));
        txt_juguete.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_juguete.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_juguete.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_juguete.setEnabled(false);
        getContentPane().add(txt_juguete, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 210, -1));

        jLabel_Cuotas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Cuotas.setText("Cuotas");
        getContentPane().add(jLabel_Cuotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, -1, -1));

        txt_Cuotas.setBackground(new java.awt.Color(153, 153, 255));
        txt_Cuotas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_Cuotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_CuotasActionPerformed(evt);
            }
        });
        getContentPane().add(txt_Cuotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 210, 30));
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 291));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ActualizarActionPerformed

        int validacion = 0;
        String juguete, jardin, comprobante, fecha, cuotas;

        juguete = txt_juguete.getText().trim();
        jardin = txt_jardin.getText().trim();
        comprobante = txt_comprobante.getText().trim();
        fecha = txt_fecha.getText().trim();
        cuotas = txt_Cuotas.getText().trim();

        if (juguete.equals("")) {
            txt_jardin.setBackground(Color.red);
            validacion++;
        }
        if (jardin.equals("")) {
            txt_juguete.setBackground(Color.red);
            validacion++;
        }
        if (comprobante.equals("")) {
            txt_comprobante.setBackground(Color.red);
            validacion++;
        }
        if (fecha.equals("")) {
            txt_fecha.setBackground(Color.red);
            validacion++;
        }

        if (validacion == 0) {

            try {

                Connection cn2 = Conexion.conectar();
                PreparedStatement pst2 = cn2.prepareStatement(
                        "update ventas set  fecha=?, FacturaNro=?, cuotas=?  "
                        + "where id_ventas = '" + ID + "'");

                
                pst2.setString(1, fecha);
                pst2.setString(2, comprobante);
                pst2.setString(3, cuotas);
                

                pst2.executeUpdate();
                cn2.close();

                JOptionPane.showMessageDialog(null, "Modificación correcta.");

            } catch (SQLException e) {
                System.err.println("Error al Actualizar." + e);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Debes llenar todos los campos.");
        }

    }//GEN-LAST:event_jButton_ActualizarActionPerformed

    private void txt_CuotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_CuotasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_CuotasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformacionVentas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformacionVentas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformacionVentas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformacionVentas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformacionVentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Actualizar;
    private javax.swing.JLabel jLabel_Contacto;
    private javax.swing.JLabel jLabel_Cuotas;
    private javax.swing.JLabel jLabel_Direccion;
    private javax.swing.JLabel jLabel_Nombre;
    private javax.swing.JLabel jLabel_RegistradoPor;
    private javax.swing.JLabel jLabel_Titulo;
    private javax.swing.JLabel jLabel_Wallpaper;
    private javax.swing.JLabel jLabel_footer;
    private javax.swing.JTextField txt_Cuotas;
    private javax.swing.JTextField txt_comprobante;
    private javax.swing.JTextField txt_fecha;
    private javax.swing.JTextField txt_jardin;
    private javax.swing.JTextField txt_juguete;
    // End of variables declaration//GEN-END:variables
}
