package ventanas;

import clases.Conexion;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.*;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.WindowConstants;

/**
 *
 * @author Javier Toro
 */
public class RegistroVentas extends javax.swing.JFrame {

    /**
     * Creates new form RegistroVentas
     */
    String user;

    public void mostrarJardin(JComboBox cmb_jardin_id) {
        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement("select * from jardines");
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                cmb_jardin_id.addItem(rs.getString("jardin"));
            }

        } catch (SQLException e) {
            System.err.println("Error en cargar jardines." + e);
            JOptionPane.showMessageDialog(null, "¡¡ERROR jardines!!, contacte al administrador.");
        }
    }

    public void mostrarJuguetes(JComboBox cmb_juguete_id) {
        try {
            Connection cn1 = Conexion.conectar();
            PreparedStatement pst = cn1.prepareStatement("select * from juguetes");
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                cmb_juguete_id.addItem(rs.getString("nombre"));
            }

        } catch (SQLException e) {
            System.err.println("Error en cargar juguetes." + e);
            JOptionPane.showMessageDialog(null, "¡¡ERROR juguetess!!, contacte al administrador.");
        }
    }

    public RegistroVentas() {
        initComponents();
        user = Login.user;

        setTitle("Registrar nueva venta - Sesión de " + user);
        setSize(620, 350);
        setResizable(false);
        setLocationRelativeTo(null);

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel_Wallpaper.getWidth(),
                jLabel_Wallpaper.getHeight(), Image.SCALE_DEFAULT));
        jLabel_Wallpaper.setIcon(icono);
        this.repaint();

        mostrarJardin(cmb_jardin_id);
        mostrarJuguetes(cmb_juguete_id);
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_Registrar = new javax.swing.JButton();
        txt_factura = new javax.swing.JTextField();
        jLabel_Juguete = new javax.swing.JLabel();
        jLabel_fecha = new javax.swing.JLabel();
        jLabel3_Factura = new javax.swing.JLabel();
        jLabel_Jardin = new javax.swing.JLabel();
        jLabel1_titulo = new javax.swing.JLabel();
        cmb_juguete_id = new javax.swing.JComboBox();
        cmb_jardin_id = new javax.swing.JComboBox();
        jDC_fecha = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel_cuotas = new javax.swing.JLabel();
        cmb_Cuotas = new javax.swing.JComboBox();
        jLabel_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_Registrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/creatividad.png"))); // NOI18N
        jButton_Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 120, 100));

        txt_factura.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txt_factura.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_factura.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_factura, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 210, -1));

        jLabel_Juguete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Juguete.setText("Juguete:");
        getContentPane().add(jLabel_Juguete, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel_fecha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_fecha.setText("Fecha de venta:");
        getContentPane().add(jLabel_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 106, -1, -1));

        jLabel3_Factura.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3_Factura.setText("Factura Nro:");
        getContentPane().add(jLabel3_Factura, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, 20));

        jLabel_Jardin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Jardin.setText("Nombre Jardin:");
        getContentPane().add(jLabel_Jardin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel1_titulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1_titulo.setText("Registro de Ventas");
        getContentPane().add(jLabel1_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        cmb_juguete_id.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione" }));
        getContentPane().add(cmb_juguete_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 210, -1));

        cmb_jardin_id.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione" }));
        getContentPane().add(cmb_jardin_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 210, -1));

        jDC_fecha.setDateFormatString("yyyy/MM/dd");
        getContentPane().add(jDC_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 200, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Guardar Registro Nuevo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jLabel_cuotas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_cuotas.setText("Plan de cuotas");
        getContentPane().add(jLabel_cuotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, -1, -1));

        cmb_Cuotas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione Cuotas", "Contado", "1 Cuota", "2 Cuotas", "3 Cuotas", "4 Cuotas", "5 Cuotas", "6 Cuotas", "7 Cuotas", "8 Cuotas", "9 Cuotas", "10 Cuotas", "11 Cuotas", "12 Cuotas", " " }));
        getContentPane().add(cmb_Cuotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 200, -1));
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RegistrarActionPerformed

        int validacion = 0, jardin_cmb, juguete_cmb, cuotas_cmb;
        String factura, string_jardin = "", string_juguete = "", string_cuotas = "";

        java.util.Date date = jDC_fecha.getDate();
        long d = date.getTime();
        java.sql.Date fecha = new java.sql.Date(d);

        factura = txt_factura.getText().trim();
        juguete_cmb = cmb_juguete_id.getSelectedIndex();
        jardin_cmb = cmb_jardin_id.getSelectedIndex();
        cuotas_cmb = cmb_Cuotas.getSelectedIndex();

        if (cuotas_cmb == 1) {
            string_cuotas = "Pago Contado";
        }
        if (cuotas_cmb == 2) {
            string_cuotas = "Cuota 1/2";
        }
        if (cuotas_cmb == 3) {
            string_cuotas = "Cuota 1/3";
        }
        if (cuotas_cmb == 4) {
            string_cuotas = "Cuota 1/4";
        }
        if (cuotas_cmb == 5) {
            string_cuotas = "Cuota 1/5";
        }
        if (cuotas_cmb == 6) {
            string_cuotas = "Cuota 1/6";
        }
        if (cuotas_cmb == 7) {
            string_cuotas = "Cuota 1/7";
        }
        if (cuotas_cmb == 8) {
            string_cuotas = "Cuota 1/8";
        }
        if (cuotas_cmb == 9) {
            string_cuotas = "Cuota 1/9";
        }
        if (cuotas_cmb == 10) {
            string_cuotas = "Cuota 1/10";
        }
        if (cuotas_cmb == 11) {
            string_cuotas = "Cuota 1/11";
        }
        if (cuotas_cmb == 12) {
            string_cuotas = "Cuota 1/12";
        }

        if (juguete_cmb != 0) {
            string_juguete = "Gusano";
        }
        if (jardin_cmb != 0) {
            string_jardin = "Cualquiera";
        }
        if (factura.equals("")) {
            txt_factura.setBackground(Color.red);
            validacion++;
        }

        if (string_jardin.equals("")) {
            cmb_jardin_id.setBackground(Color.red);
            validacion++;
        }
        if (fecha.equals("")) {
            jDC_fecha.setBackground(Color.red);
            validacion++;
        }
        if (string_juguete.equals("")) {
            cmb_juguete_id.setBackground(Color.red);
            validacion++;
        }

        if (validacion == 0) {
            try {

                Connection cn2 = Conexion.conectar();
                PreparedStatement pst2 = cn2.prepareStatement(
                        "insert into ventas values (?,?,?,?,?,?)");

                pst2.setInt(1, 0);
                pst2.setInt(2, cmb_juguete_id.getSelectedIndex());
                pst2.setInt(3, cmb_jardin_id.getSelectedIndex());
                pst2.setString(4, ((JTextField) jDC_fecha.getDateEditor().getUiComponent()).getText());
                pst2.setString(5, factura);
                pst2.setString(6, string_cuotas);

                pst2.executeUpdate();
                cn2.close();

                txt_factura.setBackground(Color.green);
                cmb_jardin_id.setBackground(Color.green);
                jDC_fecha.setBackground(Color.green);
                cmb_juguete_id.setBackground(Color.green);

                JOptionPane.showMessageDialog(null, "Registro exitoso.");
                

            } catch (SQLException e) {
                System.err.println("Error en Registrar venta." + e);
                JOptionPane.showMessageDialog(null, "¡¡ERROR al registrar!!, contacte al administrador.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debes de llenar todos los campos.");
        }

    }//GEN-LAST:event_jButton_RegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroVentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmb_Cuotas;
    private javax.swing.JComboBox cmb_jardin_id;
    private javax.swing.JComboBox cmb_juguete_id;
    private javax.swing.JButton jButton_Registrar;
    private com.toedter.calendar.JDateChooser jDC_fecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1_titulo;
    private javax.swing.JLabel jLabel3_Factura;
    private javax.swing.JLabel jLabel_Jardin;
    private javax.swing.JLabel jLabel_Juguete;
    private javax.swing.JLabel jLabel_Wallpaper;
    private javax.swing.JLabel jLabel_cuotas;
    private javax.swing.JLabel jLabel_fecha;
    private javax.swing.JTextField txt_factura;
    // End of variables declaration//GEN-END:variables

    public void Limpiar() {
        txt_factura.setText("");

    }

}
