package ventanas;

import clases.Conexion;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.*;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.WindowConstants;

/**
 *
 * @author Javier Toro
 */
public class RegistroVisitas extends javax.swing.JFrame {

    /**
     * Creates new form RegistroVisitas
     */
    String user;

    public RegistroVisitas() {
        initComponents();
        user = Login.user;

        setTitle("Registrar Visita - Sesión de " + user);
        setSize(620, 400);
        setResizable(false);
        setLocationRelativeTo(null);

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel_Wallpaper.getWidth(),
                jLabel_Wallpaper.getHeight(), Image.SCALE_DEFAULT));
        jLabel_Wallpaper.setIcon(icono);
        this.repaint();

        mostrarjardin();

    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_Registrar = new javax.swing.JButton();
        jLabel4_Fecha = new javax.swing.JLabel();
        jLabel3_Factura = new javax.swing.JLabel();
        jLabel_Jardin = new javax.swing.JLabel();
        jLabel1_titulo = new javax.swing.JLabel();
        txt_contacto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextArea_visita = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jD_fecha = new com.toedter.calendar.JDateChooser();
        cmb_jardin_id = new javax.swing.JComboBox();
        jLabel_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_Registrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/creatividad.png"))); // NOI18N
        jButton_Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 120, 100));

        jLabel4_Fecha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4_Fecha.setText("Fecha");
        getContentPane().add(jLabel4_Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 106, -1, -1));

        jLabel3_Factura.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3_Factura.setText("Con quien se hablo");
        getContentPane().add(jLabel3_Factura, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, 20));

        jLabel_Jardin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Jardin.setText("Jardin Visitado");
        getContentPane().add(jLabel_Jardin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel1_titulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1_titulo.setText("Registro de visitas a Jardines");
        getContentPane().add(jLabel1_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        txt_contacto.setBackground(new java.awt.Color(153, 153, 255));
        txt_contacto.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_contacto.setForeground(new java.awt.Color(255, 255, 255));
        txt_contacto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_contacto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_contacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 210, -1));

        TextArea_visita.setColumns(20);
        TextArea_visita.setRows(5);
        jScrollPane1.setViewportView(TextArea_visita);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 280, 160));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Comentarios");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jD_fecha.setDateFormatString("yyyy/MM/dd");
        getContentPane().add(jD_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 200, -1));

        cmb_jardin_id.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione" }));
        getContentPane().add(cmb_jardin_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 290, -1));
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RegistrarActionPerformed

        java.util.Date date = jD_fecha.getDate();
        long d = date.getTime();
        java.sql.Date fecha = new java.sql.Date(d);

        try {

            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
                    "insert into visitas values (?,?,?,?,?)");

            pst.setInt(1, 0);
            pst.setInt(2, cmb_jardin_id.getSelectedIndex());
            pst.setString(3, ((JTextField) jD_fecha.getDateEditor().getUiComponent()).getText());
            pst.setString(4, txt_contacto.getText().trim());
            pst.setString(5, TextArea_visita.getText().trim());

            pst.executeUpdate();
            cn.close();

            JOptionPane.showMessageDialog(null, "Registro exitoso.");
            this.dispose();

        } catch (SQLException e) {
            System.err.println("Error en Registrar visita." + e);
            JOptionPane.showMessageDialog(null, "¡¡ERROR al registrar!!, contacte al administrador.");
        }


    }//GEN-LAST:event_jButton_RegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroVisitas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroVisitas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroVisitas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroVisitas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroVisitas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TextArea_visita;
    private javax.swing.JComboBox cmb_jardin_id;
    private javax.swing.JButton jButton_Registrar;
    private com.toedter.calendar.JDateChooser jD_fecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1_titulo;
    private javax.swing.JLabel jLabel3_Factura;
    private javax.swing.JLabel jLabel4_Fecha;
    private javax.swing.JLabel jLabel_Jardin;
    private javax.swing.JLabel jLabel_Wallpaper;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_contacto;
    // End of variables declaration//GEN-END:variables
    void mostrarjardin() {
        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement("select * from jardines");
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                cmb_jardin_id.addItem(rs.getString("jardin"));
            }

        } catch (SQLException e) {
            System.err.println("Error en cargar jardines." + e);
            JOptionPane.showMessageDialog(null, "¡¡ERROR jardines!!, contacte al administrador.");
        }
    }

}
