package ventanas;

import clases.Conexion;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.*;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

public class RegistroJuguetes extends javax.swing.JFrame {

    /**
     * Creates new form RegistroJuguetes
     */
    String user;

    public RegistroJuguetes() {

        initComponents();
        user = Login.user;

        setTitle("Registrar nuevo Juguete - Sesión de " + user);
        setSize(640, 380);
        setResizable(false);
        setLocationRelativeTo(null);

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel_Wallpaper.getWidth(),
                jLabel_Wallpaper.getHeight(), Image.SCALE_DEFAULT));
        jLabel_Wallpaper.setIcon(icono);
        this.repaint();
        mostrarproveedor();
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Nombre = new javax.swing.JLabel();
        jLabel3_costo = new javax.swing.JLabel();
        jLabel4_precio = new javax.swing.JLabel();
        jLabel6_tipo = new javax.swing.JLabel();
        jLabel1_titulo = new javax.swing.JLabel();
        jLabel_Proveedor = new javax.swing.JLabel();
        jLabel_stock = new javax.swing.JLabel();
        cmb_tipo = new javax.swing.JComboBox<String>();
        txt_nombre = new javax.swing.JTextField();
        txt_costo = new javax.swing.JTextField();
        txt_precio = new javax.swing.JTextField();
        txt_stock = new javax.swing.JTextField();
        jButton = new javax.swing.JButton();
        cmb_proveedor = new javax.swing.JComboBox();
        jLabel_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Nombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Nombre.setText("Nombre:");
        getContentPane().add(jLabel_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel3_costo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3_costo.setText("Costo");
        getContentPane().add(jLabel3_costo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel4_precio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4_precio.setText("Precio");
        getContentPane().add(jLabel4_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 106, -1, -1));

        jLabel6_tipo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6_tipo.setText("Tipo");
        getContentPane().add(jLabel6_tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, -1));

        jLabel1_titulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1_titulo.setText("Registro de Juguetes");
        getContentPane().add(jLabel1_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        jLabel_Proveedor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Proveedor.setText("Proveedor");
        getContentPane().add(jLabel_Proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 169, -1, -1));

        jLabel_stock.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_stock.setText("Stock");
        getContentPane().add(jLabel_stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 169, -1, -1));

        cmb_tipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "seleccione", "Goma Espuma", "Madera", "Plastico" }));
        cmb_tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_tipoActionPerformed(evt);
            }
        });
        getContentPane().add(cmb_tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 200, -1));

        txt_nombre.setBackground(new java.awt.Color(153, 153, 255));
        txt_nombre.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_nombre.setForeground(new java.awt.Color(255, 255, 255));
        txt_nombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_nombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 210, -1));

        txt_costo.setBackground(new java.awt.Color(153, 153, 255));
        txt_costo.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_costo.setForeground(new java.awt.Color(255, 255, 255));
        txt_costo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_costo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_costo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 210, -1));

        txt_precio.setBackground(new java.awt.Color(153, 153, 255));
        txt_precio.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_precio.setForeground(new java.awt.Color(255, 255, 255));
        txt_precio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_precio.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 127, 210, -1));

        txt_stock.setBackground(new java.awt.Color(153, 153, 255));
        txt_stock.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_stock.setForeground(new java.awt.Color(255, 255, 255));
        txt_stock.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_stock.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 189, 210, -1));

        jButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/creatividad.png"))); // NOI18N
        jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActionPerformed(evt);
            }
        });
        getContentPane().add(jButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 120, 100));

        cmb_proveedor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "seleccione" }));
        getContentPane().add(cmb_proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 210, -1));
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActionPerformed

        int validacion = 0, tipo_cmb, proveedor_cmb;
        String nombre, costo, precio, tipo_string = "", stock;

        costo = txt_costo.getText().trim();
        nombre = txt_nombre.getText().trim();
        precio = txt_precio.getText().trim();
        proveedor_cmb = cmb_proveedor.getSelectedIndex();
        stock = txt_stock.getText().trim();
        tipo_cmb = cmb_tipo.getSelectedIndex() + 1;

        if (costo.equals("")) {
            txt_costo.setBackground(Color.red);
            validacion++;
        }
        
        if (nombre.equals("")) {
            txt_nombre.setBackground(Color.red);
            validacion++;
        }
        if (precio.equals("")) {
            txt_precio.setBackground(Color.red);
            validacion++;
        }
        
        if (stock.equals("")) {
            txt_stock.setBackground(Color.red);
            validacion++;
        }
        if(tipo_cmb == 1){
            tipo_string = "Goma Espuma";
        } else if(tipo_cmb == 2){
            tipo_string = "Madera";
        } else if(tipo_cmb == 3){
            tipo_string = "Plastico";
        }

        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
                    "select nombre from juguetes where nombre = '" + nombre + "'");
            ResultSet rs = pst.executeQuery();

            //Chequea que el nombre de juguete no este en uso
            if (rs.next()) {
                txt_nombre.setBackground(Color.red);
                JOptionPane.showMessageDialog(null, "Nombre de juguete ya en uso.");
                cn.close();
            } else {

                cn.close();

                if (validacion == 0) {
                    try {

                        Connection cn2 = Conexion.conectar();
                        PreparedStatement pst2 = cn2.prepareStatement(
                                "insert into juguetes values (?,?,?,?,?,?,?)");

                        pst2.setInt(1, 0);
                        pst2.setString(2, nombre);
                        pst2.setString(3, precio);
                        pst2.setString(4, tipo_string);
                        pst2.setString(5, costo);
                        pst2.setInt(6, cmb_proveedor.getSelectedIndex());
                        pst2.setString(7, stock);

                        pst2.executeUpdate();
                        cn2.close();

                        Limpiar();

                        txt_costo.setBackground(Color.green);
                        txt_nombre.setBackground(Color.green);
                        txt_precio.setBackground(Color.green);

                        JOptionPane.showMessageDialog(null, "Registro exitoso.");
                        this.dispose();

                    } catch (SQLException e) {
                        System.err.println("Error en Registrar juguete." + e);
                        JOptionPane.showMessageDialog(null, "¡¡ERROR al registrar!!, contacte al administrador.");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Debes de llenar todos los campos.");
                }

            }

        } catch (SQLException e) {
            System.err.println("Error en validar nombre de usario." + e);
            JOptionPane.showMessageDialog(null, "¡¡ERROR al comparar usuario!!, contacte al administrador.");
        }

    }//GEN-LAST:event_jButtonActionPerformed

    private void cmb_tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_tipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_tipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroJuguetes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroJuguetes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroJuguetes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroJuguetes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroJuguetes().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmb_proveedor;
    private javax.swing.JComboBox<String> cmb_tipo;
    private javax.swing.JButton jButton;
    private javax.swing.JLabel jLabel1_titulo;
    private javax.swing.JLabel jLabel3_costo;
    private javax.swing.JLabel jLabel4_precio;
    private javax.swing.JLabel jLabel6_tipo;
    private javax.swing.JLabel jLabel_Nombre;
    private javax.swing.JLabel jLabel_Proveedor;
    private javax.swing.JLabel jLabel_Wallpaper;
    private javax.swing.JLabel jLabel_stock;
    private javax.swing.JTextField txt_costo;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_precio;
    private javax.swing.JTextField txt_stock;
    // End of variables declaration//GEN-END:variables

    public void Limpiar() {
        txt_costo.setText("");
        txt_nombre.setText("");
        txt_precio.setText("");
        cmb_tipo.setSelectedIndex(0);
    }
        void mostrarproveedor() {
        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement("select * from proveedor");
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                cmb_proveedor.addItem(rs.getString("nombre_prov"));
            }

        } catch (SQLException e) {
            System.err.println("Error en cargar proveedores." + e);
            JOptionPane.showMessageDialog(null, "¡¡ERROR proveedores!!, contacte al administrador.");
        }
    }
}
